Repository Learnalogist/Hactoberfest_Learnalogist, pull requests merged in 2022-10, with the labels that each got.

#4 sum
  JavaScript/addtwonumbers.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#5 uuid
  JavaScript/creatingrandomuuid.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 added twoSum leetcode solution
  JavaScript/twoSum.js
Labels: hacktoberfest, hacktoberfest-accepted
